name: "postgres_dw"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "postgres_dw"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
    postgres_dw:
        # Config indicated by + and applies to all files under models/example/
        silver:
            +materialized: table # Todos os modelos em 'models/silver' ser達o tabelas
            +schema: silver # e ser達o criados no schema 'silver'
        gold:
            +materialized: view # Todos os modelos em 'models/gold' ser達o views
            +schema: gold # e ser達o criados no schema 'gold'

seeds:
    postgres_dw:
        +schema: bronze
