version: 2

# A seção 'sources' declara as tabelas brutas que seu pipeline Python cria.
sources:
    - name: raw_monitor_ar # Um nome lógico para sua fonte de dados "MonitorAr"
      schema: raw # O schema REAL no Postgres onde os dados estão
      tables:
          # Vamos supor que seu script Python juntou os 3 arquivos CSV em uma única tabela
          - name: medicoes_qualidade_ar
          - name: lista_estacoes
