version: 2

models:
    - name: dim_estacoes
      description: "Dimensão com a lista de estações de monitoramento de qualidade do ar."
      columns:
          - name: id_dim_estacao
            description: "Chave primária da dimensão de estações."
            tests:
                - unique # Garante que cada ID é único.
                - not_null # Garante que não há IDs nulos.

          - name: nome_estacao
            tests:
                - not_null
